# Generated by Django 6.0.7 on 2026-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='openai_file_id',
        ),
        migrations.AddField(
            model_name='project',
            name='memory_window',
            field=models.PositiveIntegerField(default=20, help_text='Number of recent messages to include as context (lower = cheaper)'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='gemini_file_name',
            field=models.CharField(blank=True, default='', help_text='Gemini File API resource name for deletion', max_length=500),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='gemini_uri',
            field=models.CharField(blank=True, default='', help_text='Gemini File API URI', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Gemini model to use (e.g. gemini-2.0-flash, gemini-2.5-pro)', max_length=100),
        ),
    ]
