# Generated by Django 6.0.7 on 2026-07-20 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectfile_openai_file_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-created_at'], name='projects_pr_owner_i_b5bbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_active'], name='projects_pr_owner_i_d87f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', '-uploaded_at'], name='projects_pr_project_a53d53_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['project', 'is_system_prompt', 'is_active'], name='projects_pr_project_cfab94_idx'),
        ),
    ]
