# Generated by Django 6.0.7 on 2026-07-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_projects_pr_owner_i_b5bbe3_idx_and_more'),
        ('projects', '0003_rename_gemini_fields'),
    ]

    operations = [
    ]
